### ISSUE TITLE
Change default search

### ISSUE THREAD

**Issue by oscarmorrison** [PalmerAL/min#10]
Would be useful to choose a different search provider other than DuckDuckGo.
Simply using search query strings:
eg.
https://www.google.com/?q={query}

**Comment by SteGriff** [comment]
Workaround: You can use [bangs](https://duckduckgo.com/bang) to search (practically) any other search engine from DDG. So to search Google for 'engineering', use '!g engineering', to search wikipedia, use '!wp engineering'

Hope this helps :)

**Comment by oscarmorrison** [comment]
Cheers, I forget about these
