### ISSUE TITLE
Delay opening tab navigation for a second or so

### ISSUE THREAD

**Issue by liam4** [PalmerAL/min#105]
As somebody who control-tabs all over the place, having the tab bar become huge whenever I switch tabs is really distracting. Maybe make it so that it waits a second or so before opening the navigation after pressing control-tab?

(On the topic - it might also be nice if hovering over the tab bar for a moment would open up the tab navigation, or perhaps having the navigation open when the control key is pressed *and* the mouse is hovered over the tab bar.. just spitting out ideas here -- I suppose this would better fit in a separate issue?)

**Comment by PalmerAL** [comment]
The expanded tab mode (which is what is opening when you press control+tab) is about to be removed and replaced by something else in #103. The replacement won't open unless you press shift+command+e or click a button, which should fix this issue.

> (On the topic - it might also be nice if hovering over the tab bar for a moment would open up the tab navigation, or perhaps having the navigation open when the control key is pressed and the mouse is hovered over the tab bar.. just spitting out ideas here -- I suppose this would better fit in a separate issue?)

Can you go ahead and file that in a separate issue?

**Comment by PalmerAL** [comment]
This should be fixed in 1.2.0.
