### ISSUE TITLE
Min website does not display correctly in Min browser

### ISSUE THREAD

**Issue by kafeinnet** [PalmerAL/min#12]
Hi,
![min](https://cloud.githubusercontent.com/assets/4932189/14495328/44014624-018f-11e6-9567-8655d42a3d4d.png)

That's unfortunate :).

I'm using Ubuntu 15.10 x86_64.

\fab

**Comment by PalmerAL** [comment]
It looks like the page is broken at large screen resolutions. Probably, the tour page images need to use the same CSS as the landing page.

**Comment by alextegelid** [comment]
Indeed it's only visible on a large (wide) viewport, but it's also only visible in the Min browser. Safari and Google Chrome seems to render it correctly

**Comment by PalmerAL** [comment]
Interesting, if I zoom out enough in chrome/safari/firefox, it breaks there too. Does this also happen on the home page? If not, I'll probably just copy that CSS for the tour.

**Comment by alextegelid** [comment]
That's really weird... When I zoom out in Chrome and Safari this is what I get. Safari's zoom is maxed out, but Chrome can go even smaller without it breaking.
![chrome](https://cloud.githubusercontent.com/assets/7058721/14581268/dec5cc7e-03e8-11e6-8906-19e5c760a30b.png)
![safari](https://cloud.githubusercontent.com/assets/7058721/14581269/e10cb0d8-03e8-11e6-86f4-667dc037d88c.png)

**Comment by PalmerAL** [comment]
@alextegelid That's the landing page, not the tour page. The landing page uses different CSS that doesn't have this problem.

**Comment by PalmerAL** [comment]
This should be fixed now in 3b793492bb6eb23e91700e90320abda132e4963b.
