### ISSUE TITLE
Wordpress.com rendering issues

### ISSUE THREAD

**Issue by surajsharma** [PalmerAL/min#128]
some pages in the wordpress.com blogging system aren't displayed right at all, a sample screenshot: http://puu.sh/oHQM1/3188fac979.png 

wordpress is a staple for many users and should be fully compatible with Min.

**Comment by mobdiz** [comment]
Privacy Preferens -> Uncheck "Block trackers and ads" -> Profit

**Comment by PalmerAL** [comment]
The issue was that element types were being ignored when deciding whether or not to block a resource. This meant that a rule that should only match iframes from wp.com was matching all requests to wp.com.

Fixed in b00bff46e381d5e3d3573e5937a6ab6406d8c5da.
