### ISSUE TITLE
Page returns some sort of error, but unsure what, or how to learn more about the error

### ISSUE THREAD

**Issue by CameronBanga** [PalmerAL/min#21]
![screen shot 2016-04-13 at 12 15 12 pm](https://cloud.githubusercontent.com/assets/611354/14502581/80e14422-0171-11e6-98ea-91132ad905a0.png)

Left Min open for an hour or so, and I believe sometime during this time period, I came back and saw this warning sign in the window tab bar. Not sure what the issue is, and clicking on the icon only brings the tab to the foreground or brings up the search panel. 

I'm presuming it's a rendering issue, or maybe something to do with the content blocker? Really don't know, and not sure how to debug even if I want to find out.

**Comment by PalmerAL** [comment]
The warning triangle means the page is insecure because it doesn't use HTTPS. The icon for this could probably be better though. Maybe a lock with a slash through it?

**Comment by CameronBanga** [comment]
Ah, that makes sense, but I never would have presumed that giving the icon. 

A lock with a slash through it would be much better. Ideally, it should also likely remain in the bar when the insecure tab is inactive in my opinion? The fact that the icon is only brought to the forefront when the tab is active kinda made me presume it was rendering issue.

**Comment by PalmerAL** [comment]
I've updated the icon in f9042872c179464e87cf9bdf976da79c57c6822f. It looks like this now:

<img width="328" alt="screen shot 2016-04-17 at 5 08 26 pm" src="https://cloud.githubusercontent.com/assets/10314059/14590400/180b5734-04bf-11e6-8b4e-782bd40cb156.png">

**Comment by CameronBanga** [comment]
Looks fantastic!

-- 
*Need to share a login & password with me? Don't send it unencrypted! See
my post (http://befogs.com/credentialsharing.html
<http://befogs.com/credentialsharing.html>) and send after encrypting
at http://keybase.io/cameron <http://keybase.io/cameron>.*

*Sending a bug report or app issue? Read this great post on how to send
better reports, so I can improve your
app: http://martiancraft.com/blog/2014/07/good-bug-reports/
<http://martiancraft.com/blog/2014/07/good-bug-reports/>.*

*My second book on mobile interaction design is now available! Buy
through Pearson's InformIT
<http://click.linksynergy.com/fs-bin/click?id=f*DsTpioQZM&offerid=145238.10000387&type=3&subid=0>.*
