### ISSUE TITLE
Builds and runs on Linux, but doesn't work

### ISSUE THREAD

**Issue by cassidyjames** [PalmerAL/min#23]
The window opens, but nothing works.

**Comment by cassidyjames** [comment]
Fwiw, I'm running on elementary OS .04 Loki (based on Ubuntu 16.04 Xenial Xerus)

**Comment by idle-zealot** [comment]
Experiencing what I believe to be the same issue. The page seems to be caught in a loop, reloading again and again. Running 64 bit Arch.

The binary version works fine on my system.

**Comment by PaulBGD** [comment]
Fixed with #30

**Comment by idle-zealot** [comment]
Can confirmed fixed.

**Comment by PalmerAL** [comment]
Ok, I'll close this then.
