### ISSUE TITLE
Add a way to close tabs?

### ISSUE THREAD

**Issue by schu34** [PalmerAL/min#35]
Maybe I'm just missing somthing but I can't seem to find any way to close a tab.

**Comment by mmkg** [comment]
Ctrl+W

**Comment by PalmerAL** [comment]
I've added a button to close tabs in 883809d12026cc5c1763d0415a7820ad26ee425d.

**Comment by idle-zealot** [comment]
The button causes some issues. I like that it only appears when hovering over a tab, but it's placement on the left causes the tab's title to jump around when hovered, and it seems to override the triangular warning sign that shows up on some pages, meaning one can no longer hover over the icon to see what's causing it.

**Comment by jkanarek** [comment]
Agree, lets shift it to the right side.

**Comment by PalmerAL** [comment]
This was done in f9042872c179464e87cf9bdf976da79c57c6822f.
