### ISSUE TITLE
Close tab on middle click

### ISSUE THREAD

**Issue by whitelynx** [PalmerAL/min#40]
Just about every browser I've used recently has supported closing a tab by middle-clicking on it in the tab bar; could this behavior be added to Min?

**Comment by idle-zealot** [comment]
At the moment, middle click allows for editing the url, however right click also does this, so I agree that the behavior should be changed to closing the tab.

**Comment by whitelynx** [comment]
On my copy (a fresh install of Min v1.1.1), right click on a tab actually doesn't do anything, though I'd prefer that behavior moving to right click so middle click can be used consistently with other browsers and apps. (I hadn't actually noticed at first that there was any difference between left click and middle click, but I can see how switching whether or not the URL is pre-selected can be useful)
