### ISSUE TITLE
Warning icon does nothing

### ISSUE THREAD

**Issue by RaphyRaph** [PalmerAL/min#62]
what does it mean? How can I act on this?

![image](https://cloud.githubusercontent.com/assets/3810802/14604095/7379fbbe-057a-11e6-9405-de421be60c0a.png)

**Comment by PalmerAL** [comment]
This means the page is insecure because it doesn't use HTTPS. This is a really confusing icon, and I actually just changed it yesterday to a "broken padlock" icon in f9042872c179464e87cf9bdf976da79c57c6822f. This change will be included in 1.2.0, which will be released in about two weeks.
