### ISSUE TITLE
Make it default

### ISSUE THREAD

**Issue by claudioruiz** [PalmerAL/min#67]
Is there a way to make Min the system default browser?
In OSX does not appears in to the Default Browser option in Preferences/general

**Comment by jgclark** [comment]
It seems that OSX doesn't understand this app is a browser. That's one way it shows up; a different way is that doesn't appear in the list of possible browsers that the BrowserFairy utility selects between. For me the best way to test out Min is to have it my default except for a few set sites that need Flash (yuk), or Chrome for when I'm using Google Apps.

**Comment by PalmerAL** [comment]
This is fixed for OS X in 8ceda0d102ae6be1e1241a79ca35ca524630ae2b, and will be included in the 1.2.0 release (in about 1.5 weeks).
