### ISSUE TITLE
Good old F5

### ISSUE THREAD

**Issue by burnoutberni** [PalmerAL/min#72]
F5 should reload the page.

**Comment by PalmerAL** [comment]
Can you please go to http://asquare.net/javascript/tests/KeyCode.html and post what keycode that is (for both keydown and keypress)? On macbooks, F5 controls the keyboard backlight, so I can't find out what keycode it is.

**Comment by burnoutberni** [comment]
It's ```'116'```

**Comment by PalmerAL** [comment]
Fixed in e2fb2ed9a21e9fdbf81d4cd9d8fbff8bb355c29e.
