### ISSUE TITLE
[bug] Empty tabs break Tab Grid (and possibly other things)

### ISSUE THREAD

**Issue by burnoutberni** [PalmerAL/min#75]
If I have an empty tab open (in the background or the currently used one, doesn't matter), I can't go into the Tab Grid view.

```Uncaught TypeError: Failed to construct 'URL': Invalid URL```

**Comment by PalmerAL** [comment]
Fixed in 9bbcd3d51e8e5cc47153a5b0b9df37728d034807 and cafd64012355b4e0a9447eea2406f1e5ea6e59d4.
