### ISSUE TITLE
URL Handler, Open in Min Browser not working

### ISSUE THREAD

**Issue by oscarmorrison** [PalmerAL/min#93]
Min does not seems to be able to handle opening any urls from external apps. 

E.g I have an app called Choosy (https://www.choosyosx.com) that lets me choose which browser to open certain links with. 

generally a command like: 
` open http://google.com -a /Applications/Min.app/`

should open the browser to the URL. However Min seems to have no url handling abilities.

**Comment by PalmerAL** [comment]
This was actually just fixed yesterday in 8ceda0d102ae6be1e1241a79ca35ca524630ae2b. This will be included in the 1.2.0 release, which will be released about a week from now.

**Comment by oscarmorrison** [comment]
Excellent. Thankyou!
