### ISSUE TITLE
Hide menu bar on linux?

### ISSUE THREAD

**Issue by leoc** [PalmerAL/min#97]
I use Archlinux with awesome wm with gnome and want to hide the menu bar.

Can this be done via a simple shortcut?

**Comment by idle-zealot** [comment]
This is already merged, but not included in a packaged release. Build from source to get this feature.

**Comment by PalmerAL** [comment]
To clarify what @idle-zealot said, #68 fixes this. It hides the menu bar by default, and you can press the alt key to show it. It will be included in the next (1.2.0) release.
