### ISSUE TITLE
Refresh that only reloads one tab, not entire browser window

### ISSUE THREAD

**Issue by anoxic** [PalmerAL/min#98]
I love Min, but there's one little piece that's frustrating for me. I would like to use it as I work on my own web pages, but refresh reloads the entire browser window. That is less desirable because a) it means that I have to load the content from those pages again, and when mobile I try to avoid data use, and b) often I keep a tab in the background with music streaming, reloading the entire browser messes that up.

Hopefully something like this could be added! It would make using Min much more enjoyable.

**Comment by PalmerAL** [comment]
Fixed in a50ffdd8fc55b2d812421b31d75eaa7d4739d906. After this change, pressing cmd/ctrl+r will reload the current page, ignoring the cache. Quickly pressing the same shortcut twice (within a half-second) will reload the entire browser window.
